Task1/Task1/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task1.Models;
using Task1.Models.Database;

using Task1.Models.ViewModel;

namespace Task1.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Dashboard()
        {

            Database db = new Database();
            StudentDepartment data = new StudentDepartment();
            data.Departments = db.Departments.GetAll();
            data.Students = db.Students.GetAll();
            return View(data);
        }
        public ActionResult Department()
        {
            Database db = new Database();
            var departments = db.Departments.GetAll();

            return View(departments);
        }
        public ActionResult Create()
        {
            Student s = new Student();
            Database db = new Database();
            StudentDepartment data = new StudentDepartment();
            data.Student = s;
            data.Departments = db.Departments.GetAll();
            return View(data);

        }
        [HttpPost]
        public ActionResult Create(Student s)
        {
            
            //insert to db
            if (ModelState.IsValid)
            {
                Database db = new Database();
                db.Students.Insert(s);
                return RedirectToAction("Dashboard");
            }
            return View();

        }
        public ActionResult Edit(int id)
        {

            Database db = new Database();
            var s = db.Students.Get(id);

            return View(s);
        }
        [HttpPost]
        public ActionResult Edit(Student s)
        {
            //update to db
            Database db = new Database();
            db.Students.Update(s);
            return RedirectToAction("Dashboard");
        }


        public ActionResult Delete(int id)
        {
            
            Database db = new Database();
            db.Students.Delete(id);
            return RedirectToAction("Dashboard");

        }
        [HttpPost]
        public ActionResult Login(Admin a)
        {
            if (ModelState.IsValid)
            {
                string connString = @"Server=SHEFAT\SQLEXPRESS;Database=StudentMS;Integrated Security=true;";
                SqlConnection conn1 = new SqlConnection(connString);
                string query = $"select * from Admins";
                SqlCommand cmd = new SqlCommand(query, conn1);
                conn1.Open();
                SqlDataReader reader = cmd.ExecuteReader();

                while (reader.Read())
                {

                    int Id = reader.GetInt32(reader.GetOrdinal("Id"));
                    string Name = reader.GetString(reader.GetOrdinal("Name"));
                    string UserName = reader.GetString(reader.GetOrdinal("UserName"));
                    string Password = reader.GetString(reader.GetOrdinal("Password"));
                    if (a.Password == Password && a.UserName == UserName)
                    {
                        return RedirectToAction("Dashboard");
                    }
                    else
                    {
                        ViewBag.Message = "invalid  Username or password.";
                        return View();

                    }
                }


            }
            return View();

        }
    }
}

Task1/Task1/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Task1.Controllers
{
    public class DepartmentController : Controller
    {
        // GET: Department
        public ActionResult Index()
        {
            return View();
        }
    }
}

Task1/Task1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Login Here", "Login", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <!--<div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("About", "About", "Home")</li>
            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
        </ul>
    </div>-->
        </div>
    </div>
    <div class="container body-content">

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @*@Html.ActionLink("Login tab", "Login", "Admin", new { area = "" }, new { @class = "navbar-brand" })*@
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Students", "Dashboard", "Admin")</li>
                        <li>@Html.ActionLink("Create Students", "Create", "Admin")</li>
                        <li>@Html.ActionLink("Depatments", "Department", "Admin")</li>
                    </ul>
                </div>
            </div>
        </div>

        @RenderBody()

  
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>